version: '3'

services: 
  app: 
      build: .
      container_name: keycloak_V3
      environment: 
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: postgres
        DB_SCHEMA: public
        DB_PASSWORD: 123
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports: 
        - 8080:8080
      depends_on: 
        - postgres
      volumes: 
        - ./themesr:/opt/jboss/keycloak/themes/themesr
  postgres: 
      image: postgres
      container_name: keycloak_postgres
      volumes: 
        - ./.docker/dbdata:/var/lib/postgresql/data
      restart: always
      tty: true
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123